"""A local full-text index of merged vLLM pull requests.

The index is a SQLite file, designed to be generated by a single writer and
distributed as a Git LFS artifact. Querying it never requires network access.
"""

from __future__ import annotations

import json
import re
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import requests

DEFAULT_REPOSITORY = "vllm-project/vllm"
DEFAULT_DATABASE_PATH = Path("data/vllm-pr-index.sqlite")
GITHUB_API_URL = "https://api.github.com"
SCHEMA_VERSION = 1

_FACET_PATTERNS = {
    "hardware": {
        "a100": r"\bA100\b",
        "h100": r"\bH100\b",
        "h200": r"\bH200\b",
        "b200": r"\bB200\b|\bBlackwell\b",
        "mi250": r"\bMI250\b",
        "mi300": r"\bMI300\w*\b",
        "amd": r"\bAMD\b|\bROCm\b",
        "cuda": r"\bCUDA\b",
        "tpu": r"\bTPU\b",
    },
    "architecture": {
        "llama": r"\bLlama(?:-?[234])?\b",
        "qwen": r"\bQwen\w*\b",
        "mistral": r"\bMistral\w*\b|\bMixtral\b",
        "deepseek": r"\bDeepSeek\w*\b",
        "gemma": r"\bGemma\w*\b",
        "moe": r"\bMoE\b|mixture.of.experts",
        "multimodal": r"\bVLM\b|multimodal|vision.language",
    },
    "tuning_domain": {
        "kv_cache": r"KV[ -]?cache|cache dtype|block manager",
        "attention": r"attention|FlashAttention|FlashInfer",
        "quantization": r"quantiz|\bFP8\b|\bFP4\b|\bAWQ\b|\bGPTQ\b",
        "prefill": r"prefill|prefix cach",
        "decode": r"decode|speculative",
        "parallelism": r"tensor parallel|pipeline parallel|data parallel",
        "compilation": r"torch\.compile|CUDA graph|inductor|compile",
        "scheduler": r"scheduler|scheduling|batching|max.num.seqs",
    },
}


@dataclass(frozen=True)
class PullRequestSearchResult:
    """A compact result suitable for CLI output or an agent tool response."""

    number: int
    title: str
    url: str
    merged_at: str
    author: str
    labels: list[str]
    facets: dict[str, list[str]]
    excerpt: str


class VllmPullRequestIndex:
    """Synchronize and query merged pull requests from one GitHub repository."""

    def __init__(
        self,
        database_path: str | Path = DEFAULT_DATABASE_PATH,
        repository: str = DEFAULT_REPOSITORY,
        token: Optional[str] = None,
    ) -> None:
        self.database_path = Path(database_path)
        self.repository = repository
        self.token = token

    def initialize(self) -> None:
        """Create the index schema if it does not exist."""
        self.database_path.parent.mkdir(parents=True, exist_ok=True)
        with self._connect() as connection:
            connection.executescript(
                """
                CREATE TABLE IF NOT EXISTS metadata (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS pull_requests (
                    number INTEGER PRIMARY KEY,
                    title TEXT NOT NULL,
                    body TEXT NOT NULL,
                    url TEXT NOT NULL,
                    author TEXT NOT NULL,
                    merged_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    labels_json TEXT NOT NULL,
                    files_json TEXT NOT NULL,
                    facets_json TEXT NOT NULL
                );
                CREATE VIRTUAL TABLE IF NOT EXISTS pull_requests_fts USING fts5(
                    number UNINDEXED,
                    title,
                    body,
                    labels,
                    files,
                    facets,
                    tokenize='unicode61'
                );
                """
            )
            self._set_metadata(connection, "schema_version", str(SCHEMA_VERSION))
            self._set_metadata(connection, "repository", self.repository)

    def sync(
        self,
        max_pages: Optional[int] = None,
        include_files: bool = True,
    ) -> dict[str, int | str | None]:
        """Fetch new or changed merged PRs and update the local index.

        The GitHub closed-pulls endpoint is traversed newest-first. On later
        syncs, traversal ends when it reaches the previous successful sync
        timestamp, while still upserting all PRs encountered before that point.
        Set ``include_files`` to false for a fast metadata-only initial import.
        """
        self.initialize()
        with self._connect() as connection:
            previous_sync = self._get_metadata(connection, "last_synced_at")

        scanned = 0
        indexed = 0
        page = 1
        # Match GitHub's UTC ``updated_at`` representation so lexical cursor
        # comparison remains safe on later incremental syncs.
        newest_sync = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        while max_pages is None or page <= max_pages:
            pulls = self._github_get(
                f"/repos/{self.repository}/pulls",
                {
                    "state": "closed",
                    "sort": "updated",
                    "direction": "desc",
                    "per_page": 100,
                    "page": page,
                },
            )
            if not pulls:
                break

            stop_after_page = False
            with self._connect() as connection:
                for pull in pulls:
                    scanned += 1
                    updated_at = pull.get("updated_at") or ""
                    if previous_sync and updated_at <= previous_sync:
                        stop_after_page = True
                        continue
                    if not pull.get("merged_at"):
                        continue
                    detail = pull
                    files: list[str] = []
                    if include_files:
                        detail = self._github_get(
                            f"/repos/{self.repository}/pulls/{pull['number']}"
                        )
                        files = self._get_pull_files(pull["number"])
                    self._upsert_pull_request(connection, detail, files)
                    indexed += 1
            if stop_after_page or len(pulls) < 100:
                break
            page += 1

        with self._connect() as connection:
            self._set_metadata(connection, "last_synced_at", newest_sync)
            self._set_metadata(connection, "last_sync_indexed", str(indexed))
        return {
            "repository": self.repository,
            "scanned": scanned,
            "indexed": indexed,
            "include_files": include_files,
            "last_synced_at": newest_sync,
        }

    def upsert_pull_request(
        self, pull: dict[str, Any], files: list[str] | None = None
    ) -> None:
        """Insert or replace one merged PR. Public to support deterministic imports."""
        self.initialize()
        with self._connect() as connection:
            self._upsert_pull_request(connection, pull, files)

    def _upsert_pull_request(
        self,
        connection: sqlite3.Connection,
        pull: dict[str, Any],
        files: list[str] | None = None,
    ) -> None:
        """Insert or replace one PR using an existing transaction."""
        number = int(pull["number"])
        labels = [label["name"] for label in pull.get("labels", [])]
        files = files or []
        title = pull.get("title") or ""
        body = pull.get("body") or ""
        searchable_text = "\n".join([title, body, " ".join(labels), " ".join(files)])
        facets = self._derive_facets(searchable_text)
        connection.execute("DELETE FROM pull_requests_fts WHERE number = ?", (number,))
        connection.execute(
            """
            INSERT INTO pull_requests(
                number, title, body, url, author, merged_at, updated_at,
                labels_json, files_json, facets_json
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(number) DO UPDATE SET
                title = excluded.title, body = excluded.body, url = excluded.url,
                author = excluded.author, merged_at = excluded.merged_at,
                updated_at = excluded.updated_at,
                labels_json = excluded.labels_json,
                files_json = excluded.files_json, facets_json = excluded.facets_json
            """,
            (
                number,
                title,
                body,
                pull.get("html_url") or "",
                (pull.get("user") or {}).get("login") or "",
                pull.get("merged_at") or "",
                pull.get("updated_at") or "",
                json.dumps(labels),
                json.dumps(files),
                json.dumps(facets, sort_keys=True),
            ),
        )
        connection.execute(
            (
                "INSERT INTO pull_requests_fts("
                "number, title, body, labels, files, facets) "
                "VALUES (?, ?, ?, ?, ?, ?)"
            ),
            (
                number,
                title,
                body,
                " ".join(labels),
                " ".join(files),
                self._facet_text(facets),
            ),
        )

    def search(
        self,
        query: str = "",
        architecture: Optional[str] = None,
        hardware: Optional[str] = None,
        limit: int = 10,
    ) -> list[PullRequestSearchResult]:
        """Search PR text, optionally limiting results by architecture or hardware."""
        self.initialize()
        if limit < 1:
            return []
        clauses: list[str] = []
        values: list[Any] = []
        if query.strip():
            clauses.append("pull_requests_fts MATCH ?")
            values.append(self._fts_query(query))
        if architecture:
            clauses.append("pull_requests.facets_json LIKE ?")
            values.append(f'%"{architecture.lower()}"%')
        if hardware:
            clauses.append("pull_requests.facets_json LIKE ?")
            values.append(f'%"{hardware.lower()}"%')
        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        order = (
            "bm25(pull_requests_fts), pull_requests.merged_at DESC"
            if clauses and query.strip()
            else "pull_requests.merged_at DESC"
        )
        statement = f"""
            SELECT pull_requests.number, pull_requests.title, pull_requests.url,
                   pull_requests.merged_at, pull_requests.author,
                   pull_requests.labels_json, pull_requests.facets_json,
                   snippet(pull_requests_fts, 1, '[', ']', ' … ', 24)
            FROM pull_requests
            JOIN pull_requests_fts ON pull_requests.number = pull_requests_fts.number
            {where}
            ORDER BY {order}
            LIMIT ?
        """
        values.append(limit)
        with self._connect() as connection:
            rows = connection.execute(statement, values).fetchall()
        return [
            PullRequestSearchResult(
                number=row[0],
                title=row[1],
                url=row[2],
                merged_at=row[3],
                author=row[4],
                labels=json.loads(row[5]),
                facets=json.loads(row[6]),
                excerpt=row[7] or row[1],
            )
            for row in rows
        ]

    def manifest(self) -> dict[str, Any]:
        """Return small, reviewable provenance data for the generated artifact."""
        self.initialize()
        with self._connect() as connection:
            count = connection.execute("SELECT COUNT(*) FROM pull_requests").fetchone()[
                0
            ]
            metadata = dict(connection.execute("SELECT key, value FROM metadata"))
        return {
            "repository": self.repository,
            "schema_version": SCHEMA_VERSION,
            "document_count": count,
            "generated_at": metadata.get("last_synced_at"),
            "last_sync_indexed": int(metadata.get("last_sync_indexed", "0")),
        }

    def write_manifest(self, path: str | Path) -> Path:
        """Write the index provenance manifest beside an LFS artifact."""
        output = Path(path)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(
            json.dumps(self.manifest(), indent=2) + "\n", encoding="utf-8"
        )
        return output

    def _connect(self) -> sqlite3.Connection:
        return sqlite3.connect(self.database_path)

    def _github_get(self, path: str, params: dict[str, Any] | None = None) -> Any:
        headers = {
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"
        response = requests.get(
            f"{GITHUB_API_URL}{path}", params=params, headers=headers, timeout=30
        )
        response.raise_for_status()
        return response.json()

    def _get_pull_files(self, number: int) -> list[str]:
        files: list[str] = []
        for page in range(1, 101):
            response = self._github_get(
                f"/repos/{self.repository}/pulls/{number}/files",
                {"per_page": 100, "page": page},
            )
            files.extend(item["filename"] for item in response)
            if len(response) < 100:
                break
        return files

    @staticmethod
    def _derive_facets(text: str) -> dict[str, list[str]]:
        return {
            category: [
                name
                for name, pattern in patterns.items()
                if re.search(pattern, text, re.IGNORECASE)
            ]
            for category, patterns in _FACET_PATTERNS.items()
        }

    @staticmethod
    def _facet_text(facets: dict[str, list[str]]) -> str:
        return " ".join(item for items in facets.values() for item in items)

    @staticmethod
    def _fts_query(query: str) -> str:
        terms = re.findall(r"[\w.-]+", query, flags=re.UNICODE)
        if not terms:
            raise ValueError("Search query must contain letters or numbers.")
        return " AND ".join(f'"{term.replace(chr(34), "")}"' for term in terms)

    @staticmethod
    def _get_metadata(connection: sqlite3.Connection, key: str) -> Optional[str]:
        row = connection.execute(
            "SELECT value FROM metadata WHERE key = ?", (key,)
        ).fetchone()
        return row[0] if row else None

    @staticmethod
    def _set_metadata(connection: sqlite3.Connection, key: str, value: str) -> None:
        connection.execute(
            (
                "INSERT INTO metadata(key, value) VALUES (?, ?) "
                "ON CONFLICT(key) DO UPDATE SET value = excluded.value"
            ),
            (key, value),
        )
